apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: cert-man-sa-overlay
  name: cert-manager.tanzu.vmware.com
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 2.9.1
  serviceAccountName: pkg-installs-sa
